name: My Config
version: 1.0.0
schema: v1

models:
  - name: Gemma4 Local
    provider: ollama
    model: gemma4:e2b
    apiBase: http://localhost:11434
    think : false
    
contextProviders:
  - name: codebase
  - name: file
  - name: folder
  - name: open

slashCommands:
  - name: edit
    description: Edit code in current file
  - name: comment
    description: Add comments